# CircleCI Firebase Deployment Config
version: 2
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - firebase-deploy/deploy: 
          token: '1//0dIa3lM2X3n44CgYIARAAGA0SNwF-L9Ir_3wBTaRS_E-6B_7FeUwojnzhLAL809rZyDGZOrpedwe7xKehNrwc-9ve-CtPqAwlb10'