# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: The First Step
          command:
            echo 'Firebase Deploymnt'
            echo 'This is the delivery pipeline'
      - run:
          name: Firebase Deploy
          commands: npm install -g firebase-tools
                    firebase deploy --token=$FIREBASE_TOKEN --non-interactive