version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
    deployment:
      production:
        branch: master
          commands:
            - npm install -g firebase-tools
            - firebase deploy --token=1//0dIa3lM2X3n44CgYIARAAGA0SNwF-L9Ir_3wBTaRS_E-6B_7FeUwojnzhLAL809rZyDGZOrpedwe7xKehNrwc-9ve-CtPqAwlb10 --non-interactive