version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command:
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            - npm install -g firebase-tools
            - firebase deploy --token=$FIREBASE_TOKEN --non-interactive
